### ISSUE TITLE
middleware error no signature

### ISSUE THREAD

**Issue by TitusEfferian** [line/line-bot-sdk-nodejs#109]
i'm trying to build a bot using actual same code from 
`https://github.com/line/line-bot-sdk-nodejs/tree/master/examples/echo-bot`

i changed access token and and secret with my bot credential

and i deployed it to a server

when i hit the callback by chatting my own bot
it returns error no signature like this

```
Error: no signature
    at /usr/src/app/node_modules/@line/bot-sdk/dist/middleware.js:16:18
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```

but if i change the line of code of these
```
app.post('/callback', line.middleware(config), (req, res) => {
    Promise
        .all(req.body.events.map(handleEvent))
        .then((result) => res.json(result))
        .catch((err) => {
            console.error(err);
            res.status(500).end();
        });
});
```

to

```
app.post('/callback', (req, res) => {
  Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result))
    .catch((err) => {
      console.error(err);
      res.status(500).end();
    });
});
```

it works like i expected to,
what happened in the middleware exactly?

**Comment by micksatana** [comment]
@TitusEfferian the `Verify` button seems to be used to verify webhook in very early stage of development (ie. without signature validation, simply return 200 to check if pointed correctly). When you added `line.middleware(config)`, it will validate signature and give a result as `SignatureValidationFailed`. I hope LINE Console developer added signature to the button too :)

**Comment by TitusEfferian** [comment]
okay thank you for the information
