### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by FRDS** [line/line-bot-sdk-nodejs#110]
I kept getting `UnhandledPromiseRejectionWarning` from tryting to send a sticker message:
```js
function handleMemberJoined(event) {
  event.joined.members.forEach(member => {
    return client.getProfile(member.userId)
    .then((profile) => {
      replyText(event.replyToken, `Selamat datang, ${profile.displayName} di RLID!`);
      client.replyMessage(  //Error came from this method.
        event.replyToken, {
          type:'sticker',
          stickerId:'693246',
          packageId:'2000017'
        });
    }).catch((err) => {
      return console.log(err);
    });
  })
}
```
Logs:
```
2018-12-02T02:44:06.081415+00:00 heroku[router]: at=info method=POST path="/callback" host=faradise.herokuapp.com request_id=077dc67e-20d1-4395-83e0-6f1d77748a4b fwd="203.104.146.152" dyno=web.1 connect=0ms service=309ms status=200 bytes=211 protocol=https
2018-12-02T02:44:06.549939+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
2018-12-02T02:44:06.549951+00:00 app[web.1]:     at wrapError (/app/node_modules/@line/bot-sdk/dist/http.js:10:15)
2018-12-02T02:44:06.549953+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2018-12-02T02:44:06.550068+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2018-12-02T02:44:06.550201+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Based on the logs I suspect that the error is triggered because I didn't handle the `client.replyMessage` method with `.catch()` but I saw that another method from the example code can use it with no problem:

```js
const replyText = (token, texts) => {
  texts = Array.isArray(texts) ? texts : [texts];
  return client.replyMessage(
    token,
    texts.map((text) => ({ type: 'text', text }))
  );         \\There is no catch() handler here.
};
```

So should I add `catch()` or not? TBH I prefer not to nest `catch()` in another `catch()` function.

**Comment by utatti** [comment]
I guess it's more of a question about Promise usage. If you return `client.replyMessage`, the error will be caught by the next `.catch()`. Or you can consider using async-await in Node 8.

The error itself seems because of `stickerId` and `packageId`. From bot, not every sticker can be used. About stickers which can be used via sticker message, please refer to the following document.

- https://developers.line.biz/media/messaging-api/messages/sticker_list.pdf

**Comment by FRDS** [comment]
Thank you for the answer. Looks like I was looking at the wrong direction.
