### ISSUE TITLE
Problems with axios when using http proxy

### ISSUE THREAD

**Issue by wentingd** [line/line-bot-sdk-nodejs#113]
Hi,
I was trying to use ngrok with http_proxy to tunnel my local server, so I can test a bot during development, and when I send something from the LINE client with this setup, I get the below error, where axios seems to combine proxyUrl with baseUrl in _currentUrl, making `client.replyMessage` fails:
(setting up API_BASE_URL variable also didn't help with the situation)

```
{ Error: socket hang up
    at HTTPClient.wrapError (...\node_modules\@line\bot-sdk\dist\http.js:83:20)
    at HTTPClient.instance.interceptors.response.use.err (...\node_modules\@line\bot-sdk\dist\http.js:26:88)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'ECONNRESET',
  originalError:
   { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
     code: 'ECONNRESET',
     path: undefined,
     host: undefined,
     port: 0,
     localAddress: undefined,
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        baseURL: 'https://api.line.me/v2/bot/message/reply',
        httpsAgent: [Object],
        method: 'post',
        url: 'https://api.line.me/v2/bot/message/reply/message/reply',
        data: '{"messages":[{"type":"text","text":"..."}],"replyToken":"00000000000000000000000000000000"}' },
     request:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 106,
        _requestBodyBuffers: [Array],
        _onNativeResponse: [Function],
        _currentRequest: [Object],
        _currentUrl: 'https://localhost:3128/https://api.line.me/v2/bot/message/reply/message/reply' },
     response: undefined } }
```

After a bit of digging, the problem seems related to existing issues with axios & proxy (https://github.com/axios/axios/issues/925, https://github.com/googleapis/google-auth-library-nodejs/issues/352). Calls are successful after I replace axios with this package in `http.js`:
>https://www.npmjs.com/package/axios-https-proxy-fix

Since this is more of an axios problem, and there is a workaround, not really looking for any immediate fix, but just want to point this out so in case if any changes going to be made to the http.js module, this can maybe taken into consideration...

**Comment by utatti** [comment]
I've left the issue for possible sharing to other users. I think now it's good to close this.

Thanks for your report!
