### ISSUE TITLE
[BUG] Cannot validate webhook

### ISSUE THREAD

**Issue by gie3d** [line/line-bot-sdk-nodejs#230]
## Bug Report

**Describe the bug**
There is an error during Webhook validation (the code used to work previously)
This happened in middleware when `/webhook` was called

**To Reproduce**

0. You may or may not use the code from my repo (https://github.com/gie3d/nonglinebot)
1. Used node line bot sdk and created a `/webhook` that looks like this
```node
app.post('/webhook', line.middleware(config), (req, res) => {
    Promise
        .all(req.body.events.map(handleEvent))
        .then((result) => res.json(result));
});
```
2. Test webhook from Line developers website and check the log

```
2020-06-15T08:15:23.078099+00:00 heroku[router]: at=info method=POST path="/webhook" host=qline2020.herokuapp.com request_id=5b01db7e-532a-436b-8ba5-c55993174f61 fwd="203.104.156.74" dyno=web.1 connect=1ms service=23ms status=500 bytes=404 protocol=https
2020-06-15T08:15:23.079280+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
2020-06-15T08:15:23.079323+00:00 app[web.1]:     at Hmac.update (internal/crypto/hash.js:82:11)
2020-06-15T08:15:23.079324+00:00 app[web.1]:     at Object.validateSignature [as default] (/app/node_modules/@line/bot-sdk/dist/validate-signature.js:14:69)
2020-06-15T08:15:23.079325+00:00 app[web.1]:     at _middleware (/app/node_modules/@line/bot-sdk/dist/middleware.js:36:42)
2020-06-15T08:15:23.079326+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The error seems to happen in validate-signature and the type of data seems to be incorrect but I can't investigate any further. 

**Expected behavior**
There should be no error

**Environment (please complete the following information):**
 - OS: Mac OS X 10.15.5
 - Node.js 12.6.0
 - line-bot-sdk-nodejs 6.8.4

**Comment by EriecTanijaya** [comment]
i dont have the error here, im use this

`app.use("/callback", line.middleware(config));`

then

```
app.post("/webhook", (req, res) => {
  Promise.all(req.body.events.map(handleEvent))
    .then(result => res.json(result))
    .catch(err => {
      console.error("error at app.post", err);
    });
});
```

**Comment by xingoxu** [comment]
Are you using `bodyParser` before initializing middleware?
https://line.github.io/line-bot-sdk-nodejs/guide/webhook.html#build-a-webhook-server-with-express

**Comment by xingoxu** [comment]
Sorry, I saw your code. I will try it later. Please wait a minute.

**Comment by gie3d** [comment]
Thanks @xingoxu @EriecTanijaya, it really was because of the body-parser. My apologise, the code I pushed to heroku was a little different from the git as I didn't push it to my github repo.

Changing from
```node
app.use(bodyParser.json());
app.use('/webhook', line.middleware(config));

app.post('/webhook', (req, res) => {
	Promise.all(req.body.events.map(handleLineWebHook)).then((result) => res.json(result));
});
```

to

```node
app.use('/webhook', line.middleware(config));
app.use(bodyParser.json());

app.post('/webhook', (req, res) => {
	Promise.all(req.body.events.map(handleLineWebHook)).then((result) => res.json(result));
});
```

as suggested in https://line.github.io/line-bot-sdk-nodejs/guide/webhook.html#build-a-webhook-server-with-express did solve the problem.

Many thanks.

**Comment by xingoxu** [comment]
You're welcome. As this is not a bug, I will remove the bug label.

**Comment by honam867** [comment]
hi, i have the same issue and try to fix by your way, but it did'n work

**Comment by gie3d** [comment]
If you could share your code and your errors. May be I or someone here could help.
