### ISSUE TITLE
flex message not working 

### ISSUE THREAD

**Issue by s961744** [line/line-bot-sdk-nodejs#91]
Hello,
I got an error(400) sending flex message with multicast.
Here is my flex message

> {"type":"flex","altText":"this is a flex message","contents":{"type":"bubble","body":{"type":"box","layout":"vertical","contents":[{"type":"text","text":"hello"},{"type":"text","text":"world"}]}}}

This is just a simple message from Messaging API Reference
And here's part of my log from heroku

> 2018-11-05T07:35:55.680954+00:00 app[web.1]:   statusCode: 400,
2018-11-05T07:35:55.680955+00:00 app[web.1]:   statusMessage: 'Bad Request',
2018-11-05T07:35:55.680957+00:00 app[web.1]:   originalError: 
2018-11-05T07:35:55.680958+00:00 app[web.1]:    { Error: Request failed with status code 400
2018-11-05T07:35:55.680960+00:00 app[web.1]:        at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
2018-11-05T07:35:55.680962+00:00 app[web.1]:        at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
2018-11-05T07:35:55.680963+00:00 app[web.1]:        at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:191:11)
2018-11-05T07:35:55.680965+00:00 app[web.1]:        at emitNone (events.js:110:20)
2018-11-05T07:35:55.680967+00:00 app[web.1]:        at IncomingMessage.emit (events.js:207:7)
2018-11-05T07:35:55.680969+00:00 app[web.1]:        at endReadableNT (_stream_readable.js:1045:12)
2018-11-05T07:35:55.680970+00:00 app[web.1]:        at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-11-05T07:35:55.680972+00:00 app[web.1]:        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-11-05T07:35:55.680974+00:00 app[web.1]:      config: 
2018-11-05T07:35:55.680976+00:00 app[web.1]:       { adapter: [Function: httpAdapter],
2018-11-05T07:35:55.680978+00:00 app[web.1]:         transformRequest: [Object],
2018-11-05T07:35:55.680979+00:00 app[web.1]:         transformResponse: [Object],
2018-11-05T07:35:55.680981+00:00 app[web.1]:         timeout: 0,
2018-11-05T07:35:55.680982+00:00 app[web.1]:         xsrfCookieName: 'XSRF-TOKEN',
2018-11-05T07:35:55.680984+00:00 app[web.1]:         xsrfHeaderName: 'X-XSRF-TOKEN',
2018-11-05T07:35:55.680985+00:00 app[web.1]:         maxContentLength: -1,
2018-11-05T07:35:55.680987+00:00 app[web.1]:         validateStatus: [Function: validateStatus],
2018-11-05T07:35:55.680989+00:00 app[web.1]:         headers: [Object],
2018-11-05T07:35:55.680990+00:00 app[web.1]:         method: 'post',
2018-11-05T07:35:55.680992+00:00 app[web.1]:         url: 'https://api.line.me/v2/bot/message/multicast',
2018-11-05T07:35:55.680994+00:00 app[web.1]:         data: '{"messages":[{"type":"flex","altText":"this is a flex message","contents":{"type":"bubble","body":{"type":"box","layout":"vertical","contents":[{"type":"text","text":"hello"},{"type":"text","text":"world"}]}}}],"to":["Ubaffccbd69878b950383ae88f226ba76"]}' },

Is there any wrong with this message?
Does multicast support flex message?
Thank for any help.

**Comment by utatti** [comment]
Sorry for the late response.

Multicasting flex messages hadn't been supported, but today it's been updated and now you must be able to send them.

> ## Flex Messages can now be multicast
>
> Now you can send Flex Messages with the /v2/bot/message/multicast endpoint.
>
> For the /v2/bot/message/multicast endpoint, see Send multicast messages in the Messaging API reference.

Source: https://developers.line.me/en/news/tags/messaging-api/
