### ISSUE TITLE
[BUG] Try to get a rich menu but receive "Method Not Allowed"

### ISSUE THREAD

**Issue by pudding0803** [line/line-bot-sdk-nodejs#967]
## Bug Report

**Describe the bug**
I called `getRichMenu()` with a valid rich menu ID, but I received the error message: "The request method, 'GET', is not supported," even though other rich menu methods work for me. After reviewing the source code, I couldn't find any obvious mistakes related to this problem. Additionally, when I use the method to get a rich menu from the official LINE Messaging API reference, it works as expected.

**To Reproduce**

1. call `client.getRichMenu(rich_menu_id)`, where `client` is a `MessagingApiClient`
2. See error

**Expected behavior**
Work as other functions

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Node.js Version v18.17.1
 - line-bot-sdk-nodejs version(s) v9.4.0

**Additional context**
Detailed error information
```
>  @@@@@/node_modules/@line/bot-sdk/dist/cjs/http-fetch.js:127
>              throw new exceptions_js_1.HTTPFetchError(message, {
>                    ^
>
>  HTTPFetchError: 405 - Method Not Allowed
>      at HTTPFetchClient.checkResponseStatus (@@@@@/node_modules/@line/bot-sdk/dist/cjs/http-fetch.js:127:19)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async HTTPFetchClient.get (@@@@@/node_modules/@line/bot-sdk/dist/cjs/http-fetch.js:41:9)
>      at async MessagingApiClient.getRichMenuWithHttpInfo (@@@@@/node_modules/@line/bot-sdk/dist/cjs/messaging-api/api/messagingApiClient.js:700:21)
>      at async MessagingApiClient.getRichMenu (@@@@@/node_modules/@line/bot-sdk/dist/cjs/messaging-api/api/messagingApiClient.js:690:17) {
>    status: 405,
>    statusText: 'Method Not Allowed',
>    headers: Headers {
>      [Symbol(headers list)]: HeadersList {
>        cookies: null,
>        [Symbol(headers map)]: Map(13) {
>          'server' => { name: 'Server', value: 'legy' },
>          'allow' => { name: 'Allow', value: 'POST' },
>          'content-type' => { name: 'Content-Type', value: 'application/json' },
>          'x-content-type-options' => { name: 'x-content-type-options', value: 'nosniff' },
>          'x-frame-options' => { name: 'x-frame-options', value: 'DENY' },
>          'x-line-request-id' => {
>            name: 'x-line-request-id',
>            value: '256e9e7e-1c56-4928-9d7a-4d444c41ef89'
>          },
>          'x-xss-protection' => { name: 'x-xss-protection', value: '1; mode=block' },
>          'content-length' => { name: 'Content-Length', value: '57' },
>          'expires' => { name: 'Expires', value: 'Thu, 12 Sep 2024 19:23:32 GMT' },
>          'cache-control' => {
>            name: 'Cache-Control',
>            value: 'max-age=0, no-cache, no-store'
>          },
>          'pragma' => { name: 'Pragma', value: 'no-cache' },
>          'date' => { name: 'Date', value: 'Thu, 12 Sep 2024 19:23:32 GMT' },
>          'connection' => { name: 'Connection', value: 'keep-alive' }
>        },
>        [Symbol(headers map sorted)]: null
>      },
>      [Symbol(guard)]: 'immutable',
>      [Symbol(realm)]: null
>    },
>    body: `{"message":"The request method, 'GET', is not supported"}`
>  }
```

**Comment by pudding0803** [comment]
Sorry for the incorrect report, everything's good!
